def _make_full_text(item):
    parts = [
        item.get("procedure", ""),
        item.get("joint", ""),
        item.get("body_area", ""),
        item.get("keywords", ""),
        item.get("pain_types", ""),
        item.get("product", ""),
        item.get("product_category", ""),
        item.get("technique", ""),
        item.get("contraindications", ""),
    ]
    return " ".join([p for p in parts if p]).strip()


def get_seed_procedures():
    data = [
        # Shoulder (6)
        {
            "procedure": "Arthroscopic Rotator Cuff Repair",
            "joint": "Shoulder",
            "body_area": "Shoulder",
            "keywords": "rotator cuff, supraspinatus tear, tendon repair, overhead pain",
            "pain_types": "chronic,weakness,activity-related,impingement",
            "product": "SpeedBridge™",
            "product_category": "Soft Tissue Fixation",
            "technique": "Double-row transosseous-equivalent repair with suture bridge compression.",
            "age_min": 18,
            "age_max": 75,
            "activity_level": "High",
            "recovery_weeks": 22,
            "contraindications": "severe cuff arthropathy,active infection",
            "arthrex_url": "https://www.arthrex.com/shoulder/rotator-cuff-repair",
        },
        {
            "procedure": "Bankart Repair",
            "joint": "Shoulder",
            "body_area": "Shoulder",
            "keywords": "anterior instability, labral tear, dislocation",
            "pain_types": "instability,mechanical,activity-related",
            "product": "SwiveLock®",
            "product_category": "Instability Repair",
            "technique": "Arthroscopic labral repair with capsular shift and knotless anchor fixation.",
            "age_min": 16,
            "age_max": 45,
            "activity_level": "High",
            "recovery_weeks": 18,
            "contraindications": "critical glenoid bone loss,active infection",
            "arthrex_url": "https://www.arthrex.com/shoulder/instability",
        },
        {
            "procedure": "AC Joint Stabilization",
            "joint": "Shoulder",
            "body_area": "Shoulder",
            "keywords": "ac separation, clavicle instability, coracoclavicular reconstruction",
            "pain_types": "acute,instability",
            "product": "AC TightRope®",
            "product_category": "Trauma/Instability",
            "technique": "Coracoclavicular fixation and reduction using cortical button suspensory construct.",
            "age_min": 16,
            "age_max": 60,
            "activity_level": "Medium",
            "recovery_weeks": 14,
            "contraindications": "chronic irreducible deformity,infection",
            "arthrex_url": "https://www.arthrex.com/shoulder/ac-joint",
        },
        {
            "procedure": "Shoulder InternalBrace Ligament Augmentation",
            "joint": "Shoulder",
            "body_area": "Shoulder",
            "keywords": "capsular support, ligament augmentation, recurrent instability",
            "pain_types": "instability,activity-related",
            "product": "InternalBrace™",
            "product_category": "Ligament Augmentation",
            "technique": "Suture tape augmentation of repaired ligament tissue to reinforce healing.",
            "age_min": 18,
            "age_max": 55,
            "activity_level": "High",
            "recovery_weeks": 16,
            "contraindications": "poor bone quality,active infection",
            "arthrex_url": "https://www.arthrex.com/shoulder/internalbrace",
        },
        {
            "procedure": "Remplissage for Hill-Sachs Lesion",
            "joint": "Shoulder",
            "body_area": "Shoulder",
            "keywords": "hill-sachs, engaging lesion, posterior capsule tenodesis",
            "pain_types": "instability,mechanical",
            "product": "FiberTape®",
            "product_category": "Instability Repair",
            "technique": "Infraspinatus tenodesis into humeral defect with suture tape fixation.",
            "age_min": 18,
            "age_max": 50,
            "activity_level": "High",
            "recovery_weeks": 18,
            "contraindications": "glenoid bone loss requiring bony augmentation",
            "arthrex_url": "https://www.arthrex.com/shoulder/instability",
        },
        {
            "procedure": "Arthroscopic Latarjet",
            "joint": "Shoulder",
            "body_area": "Shoulder",
            "keywords": "bone loss instability, recurrent dislocation, coracoid transfer",
            "pain_types": "instability,activity-related",
            "product": "Latarjet System",
            "product_category": "Bony Instability",
            "technique": "Coracoid transfer with fixation to restore glenoid track and stability.",
            "age_min": 18,
            "age_max": 55,
            "activity_level": "High",
            "recovery_weeks": 24,
            "contraindications": "uncontrolled seizure disorder,active infection",
            "arthrex_url": "https://www.arthrex.com/shoulder/latarjet",
        },

        # Knee (8)
        {
            "procedure": "ACL Reconstruction",
            "joint": "Knee",
            "body_area": "Knee",
            "keywords": "acl tear, instability, pivot shift, graft fixation",
            "pain_types": "instability,acute,activity-related",
            "product": "TightRope® RT",
            "product_category": "Ligament Fixation",
            "technique": "Anatomic single-bundle ACL reconstruction with suspensory fixation.",
            "age_min": 15,
            "age_max": 55,
            "activity_level": "High",
            "recovery_weeks": 24,
            "contraindications": "active infection,advanced arthrosis",
            "arthrex_url": "https://www.arthrex.com/knee/acl-reconstruction",
        },
        {
            "procedure": "All-Inside Meniscal Repair",
            "joint": "Knee",
            "body_area": "Knee",
            "keywords": "meniscus tear, joint line pain, locking",
            "pain_types": "mechanical,chronic",
            "product": "FiberStitch™",
            "product_category": "Meniscal Repair",
            "technique": "All-inside vertical and horizontal mattress meniscal fixation.",
            "age_min": 14,
            "age_max": 60,
            "activity_level": "Medium",
            "recovery_weeks": 16,
            "contraindications": "complex degenerative tear pattern",
            "arthrex_url": "https://www.arthrex.com/knee/meniscus-repair",
        },
        {
            "procedure": "Cartilage Restoration with AutoCart",
            "joint": "Knee",
            "body_area": "Knee",
            "keywords": "chondral defect, cartilage lesion, marrow stimulation",
            "pain_types": "chronic,degenerative",
            "product": "AutoCart™",
            "product_category": "Biologics/Cartilage",
            "technique": "Morselized autologous cartilage with biologic scaffold over microfracture bed.",
            "age_min": 18,
            "age_max": 55,
            "activity_level": "Medium",
            "recovery_weeks": 20,
            "contraindications": "diffuse grade 4 OA",
            "arthrex_url": "https://www.arthrex.com/knee/cartilage-restoration",
        },
        {
            "procedure": "Osteochondral Autograft Transfer",
            "joint": "Knee",
            "body_area": "Knee",
            "keywords": "focal cartilage defect, osteochondral lesion",
            "pain_types": "chronic,activity-related",
            "product": "OATS™",
            "product_category": "Cartilage Restoration",
            "technique": "Press-fit osteochondral plug transfer to restore articular congruity.",
            "age_min": 16,
            "age_max": 50,
            "activity_level": "High",
            "recovery_weeks": 22,
            "contraindications": "large bipolar lesions",
            "arthrex_url": "https://www.arthrex.com/knee/oats",
        },
        {
            "procedure": "PCL Reconstruction",
            "joint": "Knee",
            "body_area": "Knee",
            "keywords": "pcl tear, posterior instability",
            "pain_types": "instability,acute",
            "product": "SpeedTunnel™",
            "product_category": "Ligament Reconstruction",
            "technique": "Transtibial or tibial inlay reconstruction with anatomic tunnel strategy.",
            "age_min": 16,
            "age_max": 55,
            "activity_level": "High",
            "recovery_weeks": 26,
            "contraindications": "untreated posterolateral corner deficiency",
            "arthrex_url": "https://www.arthrex.com/knee/ligament-reconstruction",
        },
        {
            "procedure": "ACL Revision Reconstruction",
            "joint": "Knee",
            "body_area": "Knee",
            "keywords": "failed acl graft, tunnel widening, revision",
            "pain_types": "instability,chronic",
            "product": "GraftLink®",
            "product_category": "Revision Ligament",
            "technique": "Revision planning with graft-link construct and tunnel management.",
            "age_min": 18,
            "age_max": 60,
            "activity_level": "High",
            "recovery_weeks": 30,
            "contraindications": "active joint infection",
            "arthrex_url": "https://www.arthrex.com/knee/acl-revision",
        },
        {
            "procedure": "MPFL Reconstruction",
            "joint": "Knee",
            "body_area": "Knee",
            "keywords": "patellar instability, recurrent dislocation",
            "pain_types": "instability,mechanical",
            "product": "BioComposite SwiveLock®",
            "product_category": "Patellofemoral Stabilization",
            "technique": "Anatomic MPFL graft fixation with femoral and patellar docking points.",
            "age_min": 14,
            "age_max": 40,
            "activity_level": "High",
            "recovery_weeks": 18,
            "contraindications": "severe trochlear dysplasia without bony correction",
            "arthrex_url": "https://www.arthrex.com/knee/patellofemoral-instability",
        },
        {
            "procedure": "Meniscal Root Repair",
            "joint": "Knee",
            "body_area": "Knee",
            "keywords": "posterior root tear, extrusion, hoop stress loss",
            "pain_types": "mechanical,degenerative",
            "product": "TightRope® RT",
            "product_category": "Meniscal Repair",
            "technique": "Transtibial pullout root fixation restoring meniscal hoop function.",
            "age_min": 18,
            "age_max": 65,
            "activity_level": "Medium",
            "recovery_weeks": 20,
            "contraindications": "advanced osteoarthritis,varus malalignment untreated",
            "arthrex_url": "https://www.arthrex.com/knee/meniscus-repair",
        },

        # Hip (6)
        {
            "procedure": "Hip Labral Repair",
            "joint": "Hip",
            "body_area": "Hip",
            "keywords": "fai, labral tear, groin pain, cam lesion",
            "pain_types": "mechanical,activity-related,chronic",
            "product": "Hip Arthroscopy System",
            "product_category": "Hip Arthroscopy",
            "technique": "Labral preservation and anchor fixation after rim preparation.",
            "age_min": 16,
            "age_max": 55,
            "activity_level": "High",
            "recovery_weeks": 16,
            "contraindications": "advanced hip OA",
            "arthrex_url": "https://www.arthrex.com/hip/procedures",
        },
        {
            "procedure": "Capsular Closure and Plication",
            "joint": "Hip",
            "body_area": "Hip",
            "keywords": "microinstability, capsular laxity",
            "pain_types": "instability,activity-related",
            "product": "PushLock®",
            "product_category": "Soft Tissue Fixation",
            "technique": "Interportal capsulotomy closure with plication to reduce laxity.",
            "age_min": 18,
            "age_max": 50,
            "activity_level": "High",
            "recovery_weeks": 14,
            "contraindications": "severe dysplasia requiring reconstruction",
            "arthrex_url": "https://www.arthrex.com/hip/procedures",
        },
        {
            "procedure": "Iliopsoas Release",
            "joint": "Hip",
            "body_area": "Hip",
            "keywords": "internal snapping hip, iliopsoas tendinopathy",
            "pain_types": "mechanical,chronic",
            "product": "SutureLasso™",
            "product_category": "Hip Arthroscopy",
            "technique": "Targeted tendinous release at safe zone during arthroscopy.",
            "age_min": 18,
            "age_max": 60,
            "activity_level": "Medium",
            "recovery_weeks": 10,
            "contraindications": "hip flexor weakness with poor reserve",
            "arthrex_url": "https://www.arthrex.com/hip/procedures",
        },
        {
            "procedure": "Hip Microfracture",
            "joint": "Hip",
            "body_area": "Hip",
            "keywords": "chondral defect, acetabular cartilage lesion",
            "pain_types": "degenerative,chronic",
            "product": "Hip Arthroscopy System",
            "product_category": "Cartilage Management",
            "technique": "Microfracture awl perforation with stable rim management.",
            "age_min": 18,
            "age_max": 55,
            "activity_level": "Medium",
            "recovery_weeks": 18,
            "contraindications": "diffuse grade 4 cartilage loss",
            "arthrex_url": "https://www.arthrex.com/hip/procedures",
        },
        {
            "procedure": "FAI Osteoplasty",
            "joint": "Hip",
            "body_area": "Hip",
            "keywords": "cam, pincer, impingement",
            "pain_types": "impingement,mechanical,activity-related",
            "product": "Hip Arthroscopy System",
            "product_category": "Bony Decompression",
            "technique": "Femoral and acetabular osteoplasty to restore impingement-free ROM.",
            "age_min": 16,
            "age_max": 55,
            "activity_level": "High",
            "recovery_weeks": 14,
            "contraindications": "severe dysplasia,advanced OA",
            "arthrex_url": "https://www.arthrex.com/hip/procedures",
        },
        {
            "procedure": "Gluteus Medius Repair",
            "joint": "Hip",
            "body_area": "Hip",
            "keywords": "abductor tear, lateral hip pain",
            "pain_types": "weakness,chronic",
            "product": "PushLock®",
            "product_category": "Soft Tissue Fixation",
            "technique": "Endoscopic abductor tendon repair with anchor fixation.",
            "age_min": 30,
            "age_max": 75,
            "activity_level": "Medium",
            "recovery_weeks": 20,
            "contraindications": "severe tendon retraction with poor tissue quality",
            "arthrex_url": "https://www.arthrex.com/hip/procedures",
        },

        # Ankle/Foot (6)
        {
            "procedure": "Brostrom Lateral Ankle Repair",
            "joint": "Ankle",
            "body_area": "Foot/Ankle",
            "keywords": "atfl tear, cfl tear, recurrent ankle sprain",
            "pain_types": "instability,activity-related",
            "product": "InternalBrace™",
            "product_category": "Ligament Repair",
            "technique": "Anatomic ligament repair with suture tape augmentation.",
            "age_min": 16,
            "age_max": 60,
            "activity_level": "High",
            "recovery_weeks": 14,
            "contraindications": "severe cavovarus without correction",
            "arthrex_url": "https://www.arthrex.com/foot-ankle/procedures",
        },
        {
            "procedure": "Peroneal Tendon Repair",
            "joint": "Ankle",
            "body_area": "Foot/Ankle",
            "keywords": "peroneal split tear, lateral ankle pain",
            "pain_types": "chronic,weakness",
            "product": "BioComposite Corkscrew®",
            "product_category": "Tendon Repair",
            "technique": "Debridement and tubularization with anchor-based retinacular repair.",
            "age_min": 18,
            "age_max": 70,
            "activity_level": "Medium",
            "recovery_weeks": 16,
            "contraindications": "severe tendon degeneration",
            "arthrex_url": "https://www.arthrex.com/foot-ankle/procedures",
        },
        {
            "procedure": "Achilles Tendon Insertional Repair",
            "joint": "Ankle",
            "body_area": "Foot/Ankle",
            "keywords": "achilles rupture, insertional tendinopathy",
            "pain_types": "acute,chronic,weakness",
            "product": "SutureBridge™",
            "product_category": "Tendon Repair",
            "technique": "Double-row insertional repair with knotless bridge construct.",
            "age_min": 18,
            "age_max": 75,
            "activity_level": "Medium",
            "recovery_weeks": 18,
            "contraindications": "critical soft tissue compromise",
            "arthrex_url": "https://www.arthrex.com/foot-ankle/procedures",
        },
        {
            "procedure": "Syndesmosis Fixation",
            "joint": "Ankle",
            "body_area": "Foot/Ankle",
            "keywords": "high ankle sprain, syndesmotic disruption",
            "pain_types": "acute,instability",
            "product": "TightRope®",
            "product_category": "Trauma Fixation",
            "technique": "Dynamic syndesmotic stabilization with cortical button construct.",
            "age_min": 16,
            "age_max": 70,
            "activity_level": "High",
            "recovery_weeks": 12,
            "contraindications": "open contaminated fracture",
            "arthrex_url": "https://www.arthrex.com/foot-ankle/procedures",
        },
        {
            "procedure": "Ankle Arthroscopy Debridement",
            "joint": "Ankle",
            "body_area": "Foot/Ankle",
            "keywords": "anterior impingement, osteophyte, synovitis",
            "pain_types": "impingement,mechanical",
            "product": "NanoScope™",
            "product_category": "Arthroscopy",
            "technique": "Minimally invasive debridement of impinging soft tissue and osteophytes.",
            "age_min": 16,
            "age_max": 75,
            "activity_level": "Medium",
            "recovery_weeks": 8,
            "contraindications": "advanced tibiotalar degeneration",
            "arthrex_url": "https://www.arthrex.com/foot-ankle/procedures",
        },
        {
            "procedure": "Lisfranc Ligament Stabilization",
            "joint": "Ankle",
            "body_area": "Foot/Ankle",
            "keywords": "midfoot instability, lisfranc injury",
            "pain_types": "acute,instability",
            "product": "InternalBrace™",
            "product_category": "Midfoot Stabilization",
            "technique": "Ligament augmentation with suture tape and fixation anchors.",
            "age_min": 16,
            "age_max": 65,
            "activity_level": "Medium",
            "recovery_weeks": 14,
            "contraindications": "severe comminuted articular destruction",
            "arthrex_url": "https://www.arthrex.com/foot-ankle/procedures",
        },

        # Elbow (5)
        {
            "procedure": "UCL Reconstruction",
            "joint": "Elbow",
            "body_area": "Elbow",
            "keywords": "throwing athlete, valgus instability, ucl tear",
            "pain_types": "instability,activity-related,weakness",
            "product": "DANE TJ™",
            "product_category": "Ligament Reconstruction",
            "technique": "Docking technique reconstruction for valgus stability restoration.",
            "age_min": 16,
            "age_max": 45,
            "activity_level": "High",
            "recovery_weeks": 36,
            "contraindications": "ulnar nerve severe neuropathy untreated",
            "arthrex_url": "https://www.arthrex.com/elbow/procedures",
        },
        {
            "procedure": "Elbow Arthroscopy Synovectomy",
            "joint": "Elbow",
            "body_area": "Elbow",
            "keywords": "synovitis, loose body, stiffness",
            "pain_types": "mechanical,chronic",
            "product": "NanoScope™",
            "product_category": "Arthroscopy",
            "technique": "Compartmental synovectomy and loose body removal via arthroscopy.",
            "age_min": 18,
            "age_max": 75,
            "activity_level": "Medium",
            "recovery_weeks": 8,
            "contraindications": "severe contracture needing open release",
            "arthrex_url": "https://www.arthrex.com/elbow/procedures",
        },
        {
            "procedure": "Distal Biceps Repair",
            "joint": "Elbow",
            "body_area": "Elbow",
            "keywords": "distal biceps rupture, supination weakness",
            "pain_types": "acute,weakness",
            "product": "Arthrex Elbow System",
            "product_category": "Tendon Repair",
            "technique": "Anatomic tendon reattachment to radial tuberosity fixation construct.",
            "age_min": 18,
            "age_max": 70,
            "activity_level": "Medium",
            "recovery_weeks": 14,
            "contraindications": "chronic severe retraction not amenable to primary repair",
            "arthrex_url": "https://www.arthrex.com/elbow/procedures",
        },
        {
            "procedure": "Lateral Epicondyle Debridement and Repair",
            "joint": "Elbow",
            "body_area": "Elbow",
            "keywords": "tennis elbow, ecrb tendinosis",
            "pain_types": "chronic,activity-related",
            "product": "Arthrex Elbow System",
            "product_category": "Soft Tissue Repair",
            "technique": "Degenerative tendon debridement with extensor origin repair.",
            "age_min": 18,
            "age_max": 70,
            "activity_level": "Medium",
            "recovery_weeks": 10,
            "contraindications": "radial tunnel syndrome untreated",
            "arthrex_url": "https://www.arthrex.com/elbow/procedures",
        },
        {
            "procedure": "OLECRANON ORIF Adjunct Technique",
            "joint": "Elbow",
            "body_area": "Elbow",
            "keywords": "olecranon fracture fixation, trauma",
            "pain_types": "acute",
            "product": "Arthrex Elbow System",
            "product_category": "Trauma",
            "technique": "Fragment reduction with fixation adjuncts and triceps continuity restoration.",
            "age_min": 18,
            "age_max": 85,
            "activity_level": "Low",
            "recovery_weeks": 12,
            "contraindications": "severe open contamination",
            "arthrex_url": "https://www.arthrex.com/trauma/procedures",
        },

        # Hand/Wrist (5)
        {
            "procedure": "Scapholunate Ligament Reconstruction",
            "joint": "Hand/Wrist",
            "body_area": "Hand/Wrist",
            "keywords": "carpal instability, sl dissociation",
            "pain_types": "instability,mechanical",
            "product": "InternalBrace™",
            "product_category": "Ligament Reconstruction",
            "technique": "Carpal alignment restoration with ligament reconstruction and augmentation.",
            "age_min": 18,
            "age_max": 65,
            "activity_level": "Medium",
            "recovery_weeks": 16,
            "contraindications": "advanced SLAC wrist",
            "arthrex_url": "https://www.arthrex.com/hand-wrist/procedures",
        },
        {
            "procedure": "TFCC Repair",
            "joint": "Hand/Wrist",
            "body_area": "Hand/Wrist",
            "keywords": "ulnar-sided wrist pain, tfcc tear, druj instability",
            "pain_types": "mechanical,instability",
            "product": "SutureLasso™",
            "product_category": "Wrist Arthroscopy",
            "technique": "Arthroscopic inside-out or all-inside TFCC fixation as indicated.",
            "age_min": 16,
            "age_max": 70,
            "activity_level": "Medium",
            "recovery_weeks": 12,
            "contraindications": "advanced degenerative tfcc loss",
            "arthrex_url": "https://www.arthrex.com/hand-wrist/procedures",
        },
        {
            "procedure": "Distal Radius Arthroscopy-Assisted Fixation",
            "joint": "Hand/Wrist",
            "body_area": "Hand/Wrist",
            "keywords": "distal radius fracture, intra-articular step-off",
            "pain_types": "acute",
            "product": "NanoScope™",
            "product_category": "Trauma/Arthroscopy",
            "technique": "Arthroscopy-assisted reduction and fixation quality confirmation.",
            "age_min": 18,
            "age_max": 85,
            "activity_level": "Low",
            "recovery_weeks": 10,
            "contraindications": "open contaminated fracture",
            "arthrex_url": "https://www.arthrex.com/hand-wrist/procedures",
        },
        {
            "procedure": "CMC Thumb Stabilization",
            "joint": "Hand/Wrist",
            "body_area": "Hand/Wrist",
            "keywords": "thumb instability, cmc pain",
            "pain_types": "chronic,instability",
            "product": "SwiveLock®",
            "product_category": "Small Joint Stabilization",
            "technique": "Ligament reconstruction and suspension technique for thumb basal joint.",
            "age_min": 35,
            "age_max": 85,
            "activity_level": "Low",
            "recovery_weeks": 12,
            "contraindications": "severe fixed deformity",
            "arthrex_url": "https://www.arthrex.com/hand-wrist/procedures",
        },
        {
            "procedure": "Wrist Arthroscopy Debridement",
            "joint": "Hand/Wrist",
            "body_area": "Hand/Wrist",
            "keywords": "synovitis,chondral flap,mechanical clicking",
            "pain_types": "mechanical,chronic",
            "product": "NanoScope™",
            "product_category": "Wrist Arthroscopy",
            "technique": "Diagnostic and therapeutic arthroscopy with selective debridement.",
            "age_min": 16,
            "age_max": 80,
            "activity_level": "Medium",
            "recovery_weeks": 6,
            "contraindications": "diffuse radiocarpal arthritis",
            "arthrex_url": "https://www.arthrex.com/hand-wrist/procedures",
        },

        # Spine (5)
        {
            "procedure": "Endoscopic Lumbar Discectomy",
            "joint": "Spine",
            "body_area": "Spine",
            "keywords": "disc herniation,radiculopathy,sciatica",
            "pain_types": "acute,mechanical,weakness",
            "product": "Arthrex Endoscopic Spine System",
            "product_category": "Endoscopic Spine",
            "technique": "Transforaminal or interlaminar endoscopic decompression for nerve root relief.",
            "age_min": 18,
            "age_max": 80,
            "activity_level": "Medium",
            "recovery_weeks": 8,
            "contraindications": "cauda equina syndrome requiring urgent open intervention",
            "arthrex_url": "https://www.arthrex.com/spine/procedures",
        },
        {
            "procedure": "Endoscopic Foraminotomy",
            "joint": "Spine",
            "body_area": "Spine",
            "keywords": "foraminal stenosis,leg pain,nerve compression",
            "pain_types": "chronic,mechanical",
            "product": "Arthrex Endoscopic Spine System",
            "product_category": "Endoscopic Spine",
            "technique": "Endoscopic decompression of foraminal stenosis preserving stability.",
            "age_min": 30,
            "age_max": 85,
            "activity_level": "Low",
            "recovery_weeks": 10,
            "contraindications": "gross instability needing fusion",
            "arthrex_url": "https://www.arthrex.com/spine/procedures",
        },
        {
            "procedure": "Endoscopic Facet Cyst Resection",
            "joint": "Spine",
            "body_area": "Spine",
            "keywords": "facet cyst,claudication,radicular pain",
            "pain_types": "chronic,mechanical",
            "product": "Arthrex Endoscopic Spine System",
            "product_category": "Endoscopic Spine",
            "technique": "Endoscopic cyst decompression with targeted neural element protection.",
            "age_min": 40,
            "age_max": 85,
            "activity_level": "Low",
            "recovery_weeks": 8,
            "contraindications": "instability with spondylolisthesis requiring fusion",
            "arthrex_url": "https://www.arthrex.com/spine/procedures",
        },
        {
            "procedure": "Endoscopic Lateral Recess Decompression",
            "joint": "Spine",
            "body_area": "Spine",
            "keywords": "stenosis,neurogenic claudication,lateral recess",
            "pain_types": "degenerative,chronic,mechanical",
            "product": "Arthrex Endoscopic Spine System",
            "product_category": "Endoscopic Spine",
            "technique": "Targeted decompression for lateral recess narrowing and radicular symptoms.",
            "age_min": 45,
            "age_max": 85,
            "activity_level": "Low",
            "recovery_weeks": 10,
            "contraindications": "multilevel instability",
            "arthrex_url": "https://www.arthrex.com/spine/procedures",
        },
        {
            "procedure": "Endoscopic Revision Discectomy",
            "joint": "Spine",
            "body_area": "Spine",
            "keywords": "recurrent disc herniation,post-op leg pain",
            "pain_types": "chronic,mechanical",
            "product": "Arthrex Endoscopic Spine System",
            "product_category": "Endoscopic Spine",
            "technique": "Revision decompression through minimally invasive endoscopic access.",
            "age_min": 20,
            "age_max": 80,
            "activity_level": "Medium",
            "recovery_weeks": 10,
            "contraindications": "segmental instability requiring fusion",
            "arthrex_url": "https://www.arthrex.com/spine/procedures",
        },

        # Trauma (5)
        {
            "procedure": "Distal Fibula Fracture Fixation",
            "joint": "Trauma",
            "body_area": "Ankle",
            "keywords": "ankle fracture,orif,malleolus",
            "pain_types": "acute",
            "product": "TightRope®",
            "product_category": "Trauma Fixation",
            "technique": "Fracture reduction and fixation with syndesmotic stabilization when indicated.",
            "age_min": 16,
            "age_max": 90,
            "activity_level": "Low",
            "recovery_weeks": 12,
            "contraindications": "severe soft tissue compromise",
            "arthrex_url": "https://www.arthrex.com/trauma/procedures",
        },
        {
            "procedure": "Clavicle Fracture Fixation",
            "joint": "Trauma",
            "body_area": "Shoulder",
            "keywords": "clavicle shaft fracture, displacement",
            "pain_types": "acute",
            "product": "AC TightRope®",
            "product_category": "Trauma Fixation",
            "technique": "Open reduction and fixation with alignment restoration.",
            "age_min": 16,
            "age_max": 85,
            "activity_level": "Medium",
            "recovery_weeks": 10,
            "contraindications": "active infection",
            "arthrex_url": "https://www.arthrex.com/trauma/procedures",
        },
        {
            "procedure": "Patellar Tendon Avulsion Repair",
            "joint": "Trauma",
            "body_area": "Knee",
            "keywords": "extensor mechanism rupture,avulsion",
            "pain_types": "acute,weakness",
            "product": "FiberTape®",
            "product_category": "Trauma Soft Tissue",
            "technique": "Primary repair with augmentation to protect early healing phase.",
            "age_min": 16,
            "age_max": 75,
            "activity_level": "Medium",
            "recovery_weeks": 14,
            "contraindications": "active infection,severe tissue loss",
            "arthrex_url": "https://www.arthrex.com/trauma/procedures",
        },
        {
            "procedure": "Proximal Humerus Fracture Adjunct Stabilization",
            "joint": "Trauma",
            "body_area": "Shoulder",
            "keywords": "proximal humerus fracture,tuberosity fixation",
            "pain_types": "acute",
            "product": "PEEK Corkscrew™",
            "product_category": "Trauma Adjunct",
            "technique": "Suture-based fragment control and tuberosity balancing adjunct.",
            "age_min": 18,
            "age_max": 90,
            "activity_level": "Low",
            "recovery_weeks": 12,
            "contraindications": "non-reconstructable head split pattern",
            "arthrex_url": "https://www.arthrex.com/trauma/procedures",
        },
        {
            "procedure": "Elbow Fracture-Dislocation Ligament Repair",
            "joint": "Trauma",
            "body_area": "Elbow",
            "keywords": "terrible triad,elbow instability,fracture dislocation",
            "pain_types": "acute,instability",
            "product": "Arthrex Elbow System",
            "product_category": "Trauma/Instability",
            "technique": "Bony fixation plus collateral ligament reconstruction for stable arc.",
            "age_min": 18,
            "age_max": 85,
            "activity_level": "Low",
            "recovery_weeks": 14,
            "contraindications": "active infection,non-salvageable soft tissue",
            "arthrex_url": "https://www.arthrex.com/trauma/procedures",
        },

        # Extra coverage for 40+ total (6)
        {
            "procedure": "Subacromial Decompression",
            "joint": "Shoulder",
            "body_area": "Shoulder",
            "keywords": "impingement,bursitis,acromial spur",
            "pain_types": "impingement,chronic,activity-related",
            "product": "PEEK Corkscrew™",
            "product_category": "Arthroscopy",
            "technique": "Bursectomy with decompression and targeted bony contouring.",
            "age_min": 18,
            "age_max": 75,
            "activity_level": "Medium",
            "recovery_weeks": 8,
            "contraindications": "massive irreparable cuff pathology",
            "arthrex_url": "https://www.arthrex.com/shoulder/procedures",
        },
        {
            "procedure": "Posterior Horn Meniscus Repair",
            "joint": "Knee",
            "body_area": "Knee",
            "keywords": "posterior horn tear,locking,meniscal preservation",
            "pain_types": "mechanical,chronic",
            "product": "FiberStitch™",
            "product_category": "Meniscal Repair",
            "technique": "All-inside meniscal fixation preserving meniscal tissue.",
            "age_min": 14,
            "age_max": 60,
            "activity_level": "Medium",
            "recovery_weeks": 14,
            "contraindications": "complex irreparable tear",
            "arthrex_url": "https://www.arthrex.com/knee/procedures",
        },
        {
            "procedure": "Hip Labral Reconstruction",
            "joint": "Hip",
            "body_area": "Hip",
            "keywords": "labral deficiency,revision hip arthroscopy",
            "pain_types": "chronic,mechanical",
            "product": "SutureLasso™",
            "product_category": "Hip Preservation",
            "technique": "Segmental or circumferential labral reconstruction for suction seal restoration.",
            "age_min": 18,
            "age_max": 60,
            "activity_level": "Medium",
            "recovery_weeks": 20,
            "contraindications": "advanced OA,severe dysplasia",
            "arthrex_url": "https://www.arthrex.com/hip/procedures",
        },
        {
            "procedure": "Lateral Ligament Revision Reconstruction",
            "joint": "Ankle",
            "body_area": "Foot/Ankle",
            "keywords": "failed brostrom,revision instability",
            "pain_types": "instability,chronic",
            "product": "InternalBrace™",
            "product_category": "Revision Ligament",
            "technique": "Revision ligament reconstruction using augmented fixation strategy.",
            "age_min": 18,
            "age_max": 70,
            "activity_level": "High",
            "recovery_weeks": 18,
            "contraindications": "untreated hindfoot malalignment",
            "arthrex_url": "https://www.arthrex.com/foot-ankle/procedures",
        },
        {
            "procedure": "Ulnar Nerve Decompression at Elbow",
            "joint": "Elbow",
            "body_area": "Elbow",
            "keywords": "cubital tunnel,ulnar neuropathy",
            "pain_types": "weakness,chronic",
            "product": "Arthrex Elbow System",
            "product_category": "Nerve Decompression",
            "technique": "In-situ decompression with optional transposition based on intraoperative stability.",
            "age_min": 18,
            "age_max": 85,
            "activity_level": "Low",
            "recovery_weeks": 8,
            "contraindications": "severe denervation with limited recovery potential",
            "arthrex_url": "https://www.arthrex.com/elbow/procedures",
        },
        {
            "procedure": "Thoracolumbar Endoscopic Decompression",
            "joint": "Spine",
            "body_area": "Spine",
            "keywords": "thoracolumbar stenosis,endoscopic decompression",
            "pain_types": "degenerative,chronic,mechanical",
            "product": "Arthrex Endoscopic Spine System",
            "product_category": "Endoscopic Spine",
            "technique": "Targeted decompression of symptomatic stenotic levels through endoscopic corridor.",
            "age_min": 45,
            "age_max": 85,
            "activity_level": "Low",
            "recovery_weeks": 12,
            "contraindications": "gross deformity requiring fusion correction",
            "arthrex_url": "https://www.arthrex.com/spine/procedures",
        },
    ]

    for item in data:
        item["full_text"] = _make_full_text(item)

    return data
